alias ..='cd ..'
alias la='ls -lA'
alias ll='ls -lhACF'
alias c='clear'
alias cl='clear'
alias mk='mkdir -p'
alias rmdir='rm -rf'
alias mip='dig +short myip.opendns.com @resolver1.opendns.com'
alias fpi='nmap -sP 192.168.1.0/24 | awk '"'"'/^Nmap/{ip=$NF}/rpi/{print ip}'"'"' | sed "s/[\(\)]//g"'
alias sshpi='ssh $(fpi)'
alias electron='./node_modules/.bin/electron .'
